/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.benito.ui;

import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.itson.benito.entidades.OrdenCompra;
import mx.itson.benito.persistencia.OrdenCompraDAO;

/**
 *  Listado principal de las ordenes de compra
 * @author Emmanuel Rivas y Erick Garza
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form OrdenCompraListado
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrden = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTotal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnAbrir = new javax.swing.JMenu();
        mitArticulos = new javax.swing.JMenuItem();
        mitProveedores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Folio", "Fecha", "Proveedor", "Articulo", "Precio", "Carrito", "Subtotal", "Total", "Estado", "Observacion"
            }
        ));
        tblOrden.setGridColor(new java.awt.Color(0, 51, 153));
        jScrollPane1.setViewportView(tblOrden);

        btnAgregar.setBackground(new java.awt.Color(0, 102, 204));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(0, 102, 204));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 102, 204));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblTotal.setBackground(new java.awt.Color(0, 102, 204));
        tblTotal.setForeground(new java.awt.Color(255, 255, 255));
        tblTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Total a pagar"
            }
        ));
        jScrollPane2.setViewportView(tblTotal);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/benito/icon/michelin.png"))); // NOI18N

        btnAbrir.setText("Abrir");

        mitArticulos.setText("Articulos");
        mitArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitArticulosActionPerformed(evt);
            }
        });
        btnAbrir.add(mitArticulos);

        mitProveedores.setText("Proveedores");
        mitProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitProveedoresActionPerformed(evt);
            }
        });
        btnAbrir.add(mitProveedores);

        jMenuBar1.add(btnAbrir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar)
                        .addGap(42, 42, 42)
                        .addComponent(btnEditar)
                        .addGap(43, 43, 43)
                        .addComponent(btnEliminar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditar)
                            .addComponent(btnEliminar)
                            .addComponent(btnAgregar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // Se le pasa como parametro id de la orden el valor 0
        OrdenCompraForm form = new OrdenCompraForm(this, true, 0);
        form.setVisible(true);
        cargarTable();
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarTable();
        //Oculta al usuraio la primer columna, la cual corresponde a los id
        tblOrden.removeColumn(tblOrden.getColumnModel().getColumn(0));
    
    }//GEN-LAST:event_formWindowOpened

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

       int seleccion;
       seleccion = tblOrden.getSelectedRow();
       if(seleccion == -1){
           JOptionPane.showMessageDialog(null, "Seleccione una fila porfavor");
       }
       // Se obtiene el valor del id de la orden de compra de la tabla
       int renglon = tblOrden.getSelectedRow();
       String id = tblOrden.getModel().getValueAt(renglon, 0).toString();
       // Se abre el formulario y se le pasa el id como parámetro
       OrdenCompraForm formulario = new OrdenCompraForm(this, true, Integer.parseInt(id));
       formulario.setVisible(true);
       cargarTable(); 
  
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
  
      //Muestra una confirmacion al usuario preguntando si esta seguro que desea eliminar.
      //Si confirma, se elimina el registro y se actualiza la tabla.
      OrdenCompraDAO borrar = new OrdenCompraDAO ();
      int renglon = tblOrden.getSelectedRow();
      int id = Integer.parseInt(tblOrden.getModel().getValueAt(renglon, 0).toString());
      
      int confirmacion = JOptionPane.showConfirmDialog(this, "¿Desea eliminarlo?");
      if(confirmacion == 0){
          borrar.eliminar(id);
          JOptionPane.showMessageDialog(this, "Eliminado correctamente");
      }else if(confirmacion == 1){
      }
      cargarTable();
      
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void mitArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitArticulosActionPerformed
        // Menu item para entrar en el listado de Articulos
        ArticuloListado obj = new ArticuloListado();
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_mitArticulosActionPerformed

    private void mitProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitProveedoresActionPerformed
        // Menu item para entrar en el listado de Proveedores
        ProveedorListado obj = new ProveedorListado();
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_mitProveedoresActionPerformed
    
    /**
     * Carga todos los registros de la tabla mediante el metodo obtenerTodos y los muestra.
     */
    public void cargarTable(){
    
     List<OrdenCompra> i = OrdenCompraDAO.obtenerTodos();
         DefaultTableModel modelo =(DefaultTableModel)tblOrden.getModel();
         Locale local = new Locale("es", "MX");
         NumberFormat formatoCarrito = NumberFormat.getCurrencyInstance(local);
         SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
         modelo.setRowCount(0);
         double subtotal;
         double iva;
         double total = 0;
         for (OrdenCompra c : i ) {
            
             subtotal = c.getArticulo().getPrecio() * c.getCarrito();
             iva = subtotal * .16 + subtotal;
             total += iva;
             
            modelo.addRow(new Object[]{
                c.getId(),
                c.getFolio(),
                formatter.format(c.getFecha()),
                c.getProveedor().getNombre(),
                c.getArticulo().getNombre(),
                formatoCarrito.format(c.getArticulo().getPrecio()),
                c.getCarrito(),
                formatoCarrito.format(subtotal),
                formatoCarrito.format(iva),           
                c.getEstado(),
                c.getObservacion()
                
            });
        }
         NumberFormat formato = NumberFormat.getCurrencyInstance(local);
         DefaultTableModel modeloT = (DefaultTableModel)tblTotal.getModel();
         modeloT.setRowCount(0);
         
         modeloT.addRow(new Object[]{
                 formato.format(total)
                });
            
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnAbrir;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem mitArticulos;
    private javax.swing.JMenuItem mitProveedores;
    private javax.swing.JTable tblOrden;
    private javax.swing.JTable tblTotal;
    // End of variables declaration//GEN-END:variables
}
